version: "3.9"
services:
  backend:
    image: backendapi:latest
    build:
      context: ./CCFinal
      dockerfile: Dockerfile
    container_name: BackendAPI
    ports:
      - "5000:80"
    networks:
      - db
    depends_on:
      - dataBase
    links:
      - "dataBase:sqlserver"
  dataBase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - db

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

networks:
  db:
    driver: bridge
