version: "3.9"
services:
  backend:
    image: backendapi:latest
    build:
      context: ./CCFinal
      dockerfile: Dockerfile
    container_name: BackendAPI
    ports:
      - "5000:80"
    networks:
      - db
    depends_on:
      - dataBase
    links:
      - "dataBase:sqlserver"
  dataBase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - db

networks:
  db:
    driver: bridge
